# Generated by Django 5.1.8 on 2025-04-09 19:51

import data_import.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0002_alter_fileupload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="thumbnail",
            field=models.FileField(
                null=True, upload_to=data_import.models.upload_name_generator
            ),
        ),
    ]
