# Generated by Django 5.1.8 on 2025-04-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0003_fileupload_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileupload",
            name="thumbnail",
        ),
    ]
