# Generated by Django 4.2.19 on 2025-04-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_auto_20241107_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="start_training_on_annotation_update",
            field=models.BooleanField(
                default=True,
                help_text="Start training on annotation update",
                verbose_name="start_training_on_annotation_update",
            ),
        ),
    ]
