# Generated by Django 4.2.19 on 2025-07-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_project_start_training_on_annotation_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="model_save_name",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom name for the current model version/checkpoint. It will be used to save the model",
                null=True,
                verbose_name="model save name",
            ),
        ),
    ]
