# Generated by Django 4.2.19 on 2025-07-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_project_model_save_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="custom_weights_path",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Path on the ML backend server pointing to a custom set of weights to use.",
                null=True,
                verbose_name="custom weights path",
            ),
        ),
    ]
